version: '3.8'
services:
  db-development:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT_DEVELOPMENT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db-testing:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT_TESTING}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
  adminer:
    image: adminer
    ports:
      - "8080:8080"