export enum OrderingOrderStatus {
    Pending = 0,
    Completed = 1,
    Rejected = 2,
    DriverInBusiness = 3,
    PreparationCompleted = 4,
    RejectedByBusiness = 5,
    CanceledByDriver = 6,
    AcceptedByBusiness = 7,
    AcceptedByDriver = 8,
    PickUpCompletedByDriver = 9,
    PickUpFailedByDriver = 10,
    DeliveryCompletedByDriver = 11,
    DeliveryFailedByDriver = 12,
    Preorder = 13,
    OrderNotReady = 14,
    PickupCompletedByCustomer = 15,
    CanceledByCustomer = 16,
    NotPickedByCustomer = 17,
    DriverAlmostArrivedToBusiness = 18,
    DriverAlmostArrivedToCustomer = 19,
    CustomerAlmostArrivedToBusiness = 20,
    CustomerArrivedToBusiness = 21,
    LookingForDriver = 22,
    DriverOnWay = 23,
    DriverWaitingForOrder = 24,
    AcceptedByDriverCompany = 25,
  }